### ISSUE TITLE
Tests occasionally terminated when large files are open

### ISSUE THREAD

**Issue by deyhle** [JetBrains/mocha-intellij#2]
My Node.js Mocha tests get occasionally terminated (and not even started) with the following error output on the console:

```
/usr/local/bin/node /path/to/project/node_modules/mocha/bin/_mocha /path/to/additional/testfile --ui bdd --reporter "/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js" --recursive /path/to/project/test
[ '"postgres://configForDatabase"' ]
Error: EAGAIN: resource temporarily unavailable, write
    at Error (native)
    at Object.fs.writeSync (fs.js:658:20)
    at Object.writeSync (/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijUtil.js:129:15)
    at /Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:272:14
    at Tree.writeln (/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijTree.js:21:5)
    at TestNode.Node.register (/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijTree.js:109:13)
    at registerTestNode (/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:114:12)
    at /Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:289:9
    at Array.forEach (native)
    at /Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:288:13
    at executeSafely (/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijUtil.js:114:5)
    at Runner.<anonymous> (/Users/myuser/Library/Application Support/IntelliJIdea15/NodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js:270:5)
    at emitNone (events.js:72:20)
    at Runner.emit (events.js:166:7)
    at start (/path/to/project/node_modules/mocha/lib/runner.js:732:10)
    at Runner.run (/path/to/project/node_modules/mocha/lib/runner.js:757:5)
    at Mocha.run (/path/to/project/node_modules/mocha/lib/mocha.js:486:17)
    at Object.<anonymous> (/path/to/project/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

It happens reproducible when larger files are open (e.g. JavaScript file with more than 500 lines). When I close all open files, the tests mostly succeed. So it seems to be a performance issue…? 
My configuration: OS X 10.11.2 on rather powerful a MacBook Pro; IntelliJ IDEA 15.0.2; Node.js 4.2.3; Mocha 2.3.3.; and I use ESLint as Code Quality Tool. It is a node.js project with about 1200 Test Cases, split above various files.

**Comment by NiXXeD** [comment]
We noticed this starting to happen once we upgraded to IntelliJ 15. For us, it didn't seem to be related to file size. I've found that this error only happens when a test fails, but it doesn't _always_ happen when a test fails.

In our case, we have a test we found it on, and we can modify it to fail normally in some cases, but they don't seem to point to an obvious problem (yet). Still looking into it.

It is worth noting that I have the same configuration as you, except nowhere near that many tests.

**Comment by segrey** [comment]
@deyhle Sorry for the delay, missed the issue somehow.

Yeah, it's a known issue (https://youtrack.jetbrains.com/issue/WEB-19433). Looks like `fs.writeSync` may legally fail with `EAGAIN` and client should be ready for this. Well, mocha-intellij reporter wasn't ready for this.
It should be fixed in IntelliJ IDEA 15.0.3 #143.1821 with NodeJS plugin 143.1453.2.
@deyhle @NiXXeD Could you please try and confirm the fix?

**Comment by kuntza01** [comment]
@segrey: Updated to the versions specified. It seems to be working correctly, at least in our case that @NiXXeD referred to.

**Comment by NiXXeD** [comment]
Yep it does appear to be working in the new version. Thanks!
